### PR TITLE
RD-1786 Show Environment Type column

### PR DESCRIPTION
**Pull request by Gelio**
This PR adds support for showing data in the Environment Type column in the Deployments View.

I hope the commit log gives enough guidance about the changes :slightly_smiling_face: 

One unrelated change was fixing the way the "Status" column was presented in the widget's configuration modal (it was empty).

The functionality is covered by a Cypress test. So far, the backend does not return the `environment_type` property, so it's tested only using the mocked fixture.

## System tests

https://jenkins.cloudify.co/job/Stage-UI-System-Test/301/

Ran 2021-03-19 16:50 CET

### CODE REVIEW

**Review by qooban — APPROVED** [review]
LGTM 👍🏻

**Comment by Gelio** [comment]
I've rebased the branch on `master` to resolve merge conflicts.

What I have changed is I have renamed the `widgetConfiguration` objects to `widgetConfigurationHelpers` to avoid using the same name as the existing `widgetConfiguration` object introduced in #1253 

Aside from that, no other changes happened since the last review

**Review by qooban — DISMISSED** [review]

**Comment by qooban** [comment]
Change looks good, but there are 3 type errors in CI:
```
[2021-03-23T13:47:53.383Z] test/cypress/integration/widgets/deployments_view_spec.ts(97,33): error TS2339: Property 'toggleFieldsDropdown' does not exist on type '{ filterByParentDeployment: boolean; fieldsToShow: string[]; pageSize: number; pollingTime: number; sortColumn: string; sortAscending: boolean; }'.
[2021-03-23T13:47:53.383Z] test/cypress/integration/widgets/deployments_view_spec.ts(98,33): error TS2339: Property 'getFieldsDropdown' does not exist on type '{ filterByParentDeployment: boolean; fieldsToShow: string[]; pageSize: number; pollingTime: number; sortColumn: string; sortAscending: boolean; }'.
[2021-03-23T13:47:53.383Z] test/cypress/integration/widgets/deployments_view_spec.ts(101,33): error TS2339: Property 'toggleFieldsDropdown' does not exist on type '{ filterByParentDeployment: boolean; fieldsToShow: string[]; pageSize: number; pollingTime: number; sortColumn: string; sortAscending: boolean; }'.
```
so just let me know once fixed, I'll re-review.

**Comment by Gelio** [comment]
Yup, that's what I get for having too many branches depend on one another :slightly_smiling_face: I've fixed the TS errors. I suggest not rerunning the system tests again since not much has changed since the last time I ran them :slightly_smiling_face:

**Review by qooban — APPROVED** [review]
